CREATE SEQUENCE IF NOT EXISTS leader_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE leader
(
    id        BIGINT       NOT NULL,
    fname     VARCHAR(50)  NOT NULL,
    lname     VARCHAR(50)  NOT NULL,
    job_title VARCHAR(255) NOT NULL,
    CONSTRAINT pk_leader PRIMARY KEY (id)
);

CREATE TABLE review
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    leader_id          BIGINT                                  NOT NULL,
    leader_rating      INTEGER                                 NOT NULL,
    review_description TEXT                                    NOT NULL,
    date_of_review     date                                    NOT NULL,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_LEADER FOREIGN KEY (leader_id) REFERENCES leader (id);